#!/bin/bash -ex

EASY_RSA=/etc/openvpn/easy-rsa
HTDOCS=/var/www/openvpn/htdocs
SRC=/usr/local/src

# enable ip forwarding
sed -i "/^#net.ipv4.ip_forward=1/ s/#//" /etc/sysctl.conf

mkdir -p $EASY_RSA
cp -u /usr/share/easy-rsa/* $EASY_RSA

# tweak crl scripts for crl.jail
for i in list-crl revoke-full; do
    sed -i 's|^\(CRL=\).*|\1"crl.jail/crl.pem"|' $EASY_RSA/$i
done

# webserver related
mkdir -p /var/www/openvpn/logs
chown www-data:www-data /var/www/openvpn/logs
lighty-disable-mod ssl

mkdir -p $HTDOCS/{css,images}
cp /var/www/js/ui.* $HTDOCS/js/
cp /var/www/css/*.css $HTDOCS/css/
cp /var/www/images/{webmin.png,shell.png,tab.png} $HTDOCS/images/
rm -rf /var/www/{js,css,images}

# fix pkitool bug
sed -i 's|\(KEY_ALTNAMES=\)"$KEY_CN"|\1"DNS:$KEY_CN"|' /etc/openvpn/easy-rsa/pkitool

# temporary fix to https://github.com/turnkeylinux/tracker/issues/1200
ln -s /etc/openvpn/easy-rsa/openssl-1.0.0.cnf /etc/openvpn/easy-rsa/openssl.cnf

# enable default vpnserver config on boot
systemctl enable openvpn@server

# enable openvpn-tun service (creates /dev/net/tun device in containers - closes #1011)
systemctl enable openvpn-tun.service
