#!/bin/bash -e
# initialize openvpn easy-rsa, server keys and configuration

# shellcheck source=/dev/null
source /etc/default/inithooks

if [[ -e $INITHOOKS_CONF ]]; then
   source "$INITHOOKS_CONF"
fi

# skip initialization if headless (will be configured by turnkey-init) 
if [[ "$APP_DOMAIN" == "DEFAULT" ]]; then
   exit 0
fi

"$INITHOOKS_PATH/bin/openvpn.py" \
   --profile="$APP_PROFILE" \
   --public-address="$APP_DOMAIN" \
   --virtual-subnet="$APP_VIRTUAL_SUBNET" \
   --private-subnet="$APP_PRIVATE_SUBNET" \
   --key-email="$APP_EMAIL"
